# Generated by Django 6.0 on 2026-01-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('distribution', models.CharField(max_length=255)),
                ('distribution_version', models.CharField(max_length=255)),
                ('os_family', models.CharField(max_length=255)),
                ('cpu_cores', models.IntegerField()),
                ('memory_mb', models.IntegerField()),
                ('devices', models.JSONField()),
                ('mounts', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
